#!/usr/bin/env python3
import os
import textwrap
import psycopg
from dotenv import load_dotenv

load_dotenv()
load_dotenv(".env.local", override=True)
DATABASE_URL = os.getenv("DATABASE_URL")
assert DATABASE_URL, "Set DATABASE_URL in .env"

SCHEMA_SQL = textwrap.dedent(
    """
-- Extensions
create extension if not exists pgcrypto;  -- for gen_random_uuid()

-- Enums
do $$ begin
  if not exists (select 1 from pg_type where typname = 'post_status') then
    create type post_status as enum ('draft','scheduled','posted','failed');
  end if;
  if not exists (select 1 from pg_type where typname = 'media_type') then
    create type media_type as enum ('none','image','video','carousel');
  end if;
  if not exists (select 1 from pg_type where typname = 'platform') then
    create type platform as enum ('instagram','facebook','tiktok','x','linkedin');
  end if;
  if not exists (select 1 from pg_type where typname = 'compliance_result') then
    create type compliance_result as enum ('pass','flag','fail');
  end if;
end $$;

-- Tables
create table if not exists books (
  book_id text primary key,                 -- slug: title-author-isbn13
  title text not null,
  subtitle text,
  author_primary text not null,
  author_secondary text,
  isbn13 char(13) unique not null,
  publisher text,
  pub_year int,
  category text,
  cover_url text,
  tags text[],
  created_at timestamptz default now()
);

-- Add affiliate link storage
alter table books add column if not exists affiliate_url text;

create table if not exists quotes (
  quote_id uuid primary key default gen_random_uuid(),
  book_id text not null references books(book_id) on delete cascade,
  quote_text text not null,
  location_type text,
  location_value text,
  source_name text,
  source_url text,
  popularity_hint text,
  my_commentary text,
  is_approved boolean default false,
  created_at timestamptz default now(),
  constraint chk_quote_len check (length(quote_text) <= 1200)
);

-- Quote lifecycle flags (for prepublish selection workflow)
alter table quotes add column if not exists is_drafted boolean default false;
alter table quotes add column if not exists drafted_at timestamptz;
alter table quotes add column if not exists is_discarded boolean default false;
alter table quotes add column if not exists discarded_at timestamptz;

create table if not exists publications (
  publication_id uuid primary key default gen_random_uuid(),
  book_id text not null references books(book_id) on delete cascade,
  planned_at timestamptz,
  status post_status default 'draft',
  intro_text text,
  outro_text text,
  affiliate_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists publication_quotes (
  publication_id uuid not null references publications(publication_id) on delete cascade,
  quote_id uuid references quotes(quote_id) on delete set null,
  position int check (position between 1 and 6),
  primary key (publication_id, position)
);

create table if not exists platform_posts (
  platform_post_id uuid primary key default gen_random_uuid(),
  publication_id uuid not null references publications(publication_id) on delete cascade,
  platform platform not null,
  media_type media_type not null default 'none',
  caption text,
  asset_url text,
  post_url text,
  is_scheduled boolean default false,
  scheduled_for timestamptz,
  posted_at timestamptz,
  metrics_24h jsonb,
  metrics_7d jsonb,
  created_at timestamptz default now(),
  unique (publication_id, platform)
);

create table if not exists compliance_checks (
  check_id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references quotes(quote_id) on delete cascade,
  rule_version text not null,
  quote_word_count int not null,
  has_commentary boolean not null,
  duplicate_elsewhere boolean default false,
  verdict compliance_result not null,
  notes text,
  checked_at timestamptz default now()
);

create table if not exists sources (
  source_id bigserial primary key,
  book_id text references books(book_id) on delete cascade,
  source_type text not null,
  source_name text,
  source_link text,
  rank int,
  week_of date,
  created_at timestamptz default now()
);

create table if not exists scores (
  book_id text primary key references books(book_id) on delete cascade,
  signal_strength int,
  virality_guess int,
  evergreen int,
  personal_fit int,
  composite_score numeric
);

-- Images generated by prepublish (tracks which quote produced which file)
create table if not exists generated_images (
  image_id uuid primary key default gen_random_uuid(),
  book_id text references books(book_id) on delete cascade,
  quote_id uuid references quotes(quote_id) on delete set null,
  is_cta boolean default false,
  run_key text,
  file_path text not null,
  width int,
  height int,
  file_hash text,
  created_at timestamptz default now()
);

-- Captions generated by prepublish (tracks final caption text per run)
create table if not exists generated_captions (
  caption_id uuid primary key default gen_random_uuid(),
  book_id text references books(book_id) on delete cascade,
  run_key text,
  variant text, -- 'ig' or 'fb'
  caption_path text not null,
  caption_text text not null,
  confirmed_at timestamptz,
  created_at timestamptz default now()
);

-- In case table exists without new columns
alter table generated_captions add column if not exists variant text;
alter table generated_captions add column if not exists confirmed_at timestamptz;

-- Indexes
create index if not exists quotes_book_idx on quotes(book_id);
create index if not exists quotes_approved_idx on quotes(is_approved);
create index if not exists books_isbn_idx on books(isbn13);
create index if not exists sources_week_idx on sources(week_of);
create index if not exists publications_status_idx on publications(status);
create index if not exists platform_posts_sched_idx on platform_posts(is_scheduled, scheduled_for);
create index if not exists quotes_flags_idx on quotes(is_discarded, is_drafted, book_id);
create index if not exists gen_images_book_idx on generated_images(book_id);
create index if not exists gen_images_quote_idx on generated_images(quote_id);
create index if not exists gen_images_run_idx on generated_images(run_key);
create index if not exists gen_captions_book_idx on generated_captions(book_id);
create index if not exists gen_captions_run_idx on generated_captions(run_key);
create index if not exists gen_captions_variant_idx on generated_captions(variant);
create index if not exists quotes_flags_idx on quotes(is_discarded, is_drafted, book_id);

-- Trigger to require commentary + approval before scheduling/posting
create or replace function prevent_uncommented_publish()
returns trigger as $$
begin
  if new.status in ('scheduled','posted') then
    if exists (
      select 1
      from publication_quotes pq
      join quotes q on q.quote_id = pq.quote_id
      where pq.publication_id = new.publication_id
        and (q.is_approved = false or q.my_commentary is null or length(trim(q.my_commentary)) < 30)
    ) then
      raise exception 'Cannot schedule/post: all quotes must be approved and include commentary (>=30 chars).';
    end if;
  end if;
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists tg_publications_guard on publications;
create trigger tg_publications_guard
before update on publications
for each row execute function prevent_uncommented_publish();
"""
)


def main():
    print("Connecting to Postgres…")
    with psycopg.connect(DATABASE_URL) as conn:
        with conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)
        conn.commit()
    print("Schema installed. ✅")


if __name__ == "__main__":
    main()
